server.port=${PORT:8080}
server.servlet.context-path=/api

spring.datasource.url=${DB_URL:jdbc:h2:mem:testdb}
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:Rahul133}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=${JWT_SECRET:mysecretkey12345678901234567890123456789012}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}